[project]
name = "poster-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pillow>=11.3.0",
    "requests>=2.32.4",
    "boto3>=1.34.0",
    "python-dotenv>=1.0.0",
]
