name: Docker Build Test

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'main.py'
      - '.github/workflows/docker-*.yml'

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test image functionality
        run: |
          # Build the image locally
          docker build -t poster-generator-test .
          
          # Test that the image starts correctly (should fail due to missing API key)
          # We expect this to fail with our specific error message
          if docker run --rm poster-generator-test 2>&1 | grep -q "TMDB_API_KEY not set"; then
            echo "✅ Docker image works correctly - shows expected error for missing API key"
          else
            echo "❌ Docker image test failed"
            exit 1
          fi